#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-cloudevents
Version  : 1.9.0
Release  : 1
URL      : https://files.pythonhosted.org/packages/35/51/e4beea7af2e9a6f50b2a13e57444aa879d5366fb177b9d7bcf613de29696/cloudevents-1.9.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/35/51/e4beea7af2e9a6f50b2a13e57444aa879d5366fb177b9d7bcf613de29696/cloudevents-1.9.0.tar.gz
Summary  : CloudEvents Python SDK
Group    : Development/Tools
License  : Apache-2.0
Requires: pypi-cloudevents-license = %{version}-%{release}
Requires: pypi-cloudevents-python = %{version}-%{release}
Requires: pypi-cloudevents-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(deprecation)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
# Python SDK for [CloudEvents](https://github.com/cloudevents/spec)
[![PyPI version](https://badge.fury.io/py/cloudevents.svg)](https://badge.fury.io/py/cloudevents)

%package license
Summary: license components for the pypi-cloudevents package.
Group: Default

%description license
license components for the pypi-cloudevents package.


%package python
Summary: python components for the pypi-cloudevents package.
Group: Default
Requires: pypi-cloudevents-python3 = %{version}-%{release}

%description python
python components for the pypi-cloudevents package.


%package python3
Summary: python3 components for the pypi-cloudevents package.
Group: Default
Requires: python3-core
Provides: pypi(cloudevents)
Requires: pypi(deprecation)

%description python3
python3 components for the pypi-cloudevents package.


%prep
%setup -q -n cloudevents-1.9.0
cd %{_builddir}/cloudevents-1.9.0
pushd ..
cp -a cloudevents-1.9.0 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1675273850
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export FCFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export FFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export CXXFLAGS="$CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export MAKEFLAGS=%{?_smp_mflags}
python3 -m build --wheel --skip-dependency-check --no-isolation
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 -m build --wheel --skip-dependency-check --no-isolation

popd

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-cloudevents
cp %{_builddir}/cloudevents-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/pypi-cloudevents/7df059597099bb7dcf25d2a9aedfaf4465f72d8d || :
pip install --root=%{buildroot} --no-deps --ignore-installed dist/*.whl
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
pip install --root=%{buildroot}-v3 --no-deps --ignore-installed dist/*.whl
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-cloudevents/7df059597099bb7dcf25d2a9aedfaf4465f72d8d

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
